import fs from "node:fs";
import path from "node:path";

// Generates supabase/functions/_shared/prompts.ts from coach-prompts/*.md.
//
// Why this exists: the chat edge function originally read these files at
// runtime with Deno.readTextFile(new URL("../../../coach-prompts/...")) —
// works fine locally, but Supabase's function deploy only uploads files
// reachable via a *static* import graph. A live deploy confirmed this:
// the file simply isn't present at runtime (`NotFound: path not found:
// /var/tmp/coach-prompts/core-rules.md`). Embedding the content as
// exported string constants in a module the function actually `import`s
// is the same fix already used for packages/core (see
// supabase/functions/_shared/core/README.md) — bring the content into
// the static graph, don't reach for it at runtime.
//
// coach-prompts/*.md stays the single source of truth. Re-run this
// script after editing any prompt file; the generated output is a build
// artifact, never hand-edited.
//
// Usage: npx tsx generate-edge-prompts.ts

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT_PATH = path.join(ROOT, "supabase", "functions", "_shared", "prompts.ts");

function readMd(relPath: string): string {
  return fs.readFileSync(path.join(ROOT, relPath), "utf-8");
}

const coreRules = readMd("coach-prompts/core-rules.md");
const personalities = {
  "drill-sergeant": readMd("coach-prompts/personalities/drill-sergeant.md"),
  mentor: readMd("coach-prompts/personalities/mentor.md"),
  hype: readMd("coach-prompts/personalities/hype.md"),
};
const proactiveExtension = readMd("coach-prompts/proactive-extension.md");

const output = `// GENERATED by scripts/generate-edge-prompts.ts from coach-prompts/*.md.
// Do not hand-edit — edit the source .md files and re-run the script.
// See supabase/functions/_shared/core/README.md for why generated/vendored
// content lives here: the edge function bundler only uploads what's
// reachable via a static import, and these were previously read at
// runtime from a path outside the function's upload graph.

export const CORE_RULES = ${JSON.stringify(coreRules)};

export const PERSONALITY_PROMPTS: Record<"drill-sergeant" | "mentor" | "hype", string> = {
  "drill-sergeant": ${JSON.stringify(personalities["drill-sergeant"])},
  mentor: ${JSON.stringify(personalities.mentor)},
  hype: ${JSON.stringify(personalities.hype)},
};

export const PROACTIVE_EXTENSION = ${JSON.stringify(proactiveExtension)};
`;

fs.writeFileSync(OUT_PATH, output);
console.log(`Wrote ${OUT_PATH} (${output.length} bytes)`);
